export { dialogsReducer, sendMessage, updateNewMessageBody } from './dialogsPage-reducer'
export { postReducer, addPosts, setChangeText } from './postPage-reducer'
export { asideReducer } from './asideBlock-reducer'
export { usersReducer } from './usersPage-reducer'
export { authReducer } from './auth-Reducer'
