export { dialogsReducer, sendMessage } from './dialogsPage-reducer'
export { postReducer, addPosts } from './postPage-reducer'
export { asideReducer } from './asideBlock-reducer'
export { usersReducer } from './usersPage-reducer'
export { authReducer } from './auth-Reducer'
