export { Profile } from './Profile'
export { Messages } from './Messages'
export { News } from './News'
export { SettingPage } from './SettingPage'
export { Music } from './Music'
export { Login } from './Login'
